nelmio_api_doc:
    documentation:
        info:
            title: Roasting Reels API Documentation
            description: This is a movie reviews app!
            version: 1.0.0

        components:
            securitySchemes:
                bearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT

            security:
                - bearerAuth: []

        paths:
            /api/login_check:
                post:
                    tags: ["authentication"]
                    summary: "Authenticate user and retrieve JWT token"
                    requestBody:
                        description: "User credentials"
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        username:
                                            type: string
                                        password:
                                            type: string
                    responses:
                        '200':
                            description: "Authentication successful"
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                        '401':
                            description: "Invalid credentials"



    areas: # to filter documented areas
        path_patterns:
            #- ^/api(?!/doc$) # Accepts routes under /api except /api/doc to be documented. /api/doc is the route for the Swagger UI documentation.
            - ^/api # Includes route to the documentation