// Test the get all movies endpoint
GET http://localhost:8000/api/v1/movies
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MTMzMDkzMDEsImV4cCI6MTcxMzM1MjUwMSwicm9sZXMiOlsiUk9MRV9FRElUT1IiLCJST0xFX1VTRVIiXSwidXNlcm5hbWUiOiJyLnBlbnJvc2VAcm9hc3RpbmdyZWVscy5lZGl0b3IuY29tIn0.SfiA46Yq_AqgVIKzS7cvkhgiWzgItJjPAV9m3vRS6zQmGLHKMhCiEwcSWZeeoLXKdvdTD591eCbSL8nctWJ02YzpA0lFY-BI445Hp-eKQsu4cg_2qathq34KddLt2J7d4jCcnIYdfg8Pn3SkllC5Va7DXrJuARExc9AYzh-F9YepDCAKQVCLs_4IuFO3-0St2ICc0cmJOKLkn_-hKZbHMX1FpZnqM7M1Wqnrycr_hJlzTpA4EXBvDyJ-ekOh9sQj0j3f5hzzTG2pohCoy4EhC3c-RTDfGyUJ9ky99pD34Hu93XfBVoKf1v_LgxOr_lg9tG3gm8hD9lYEGmj-BPjGXQ
Accept: application/json


