// Test the get movie by id endpoint
GET http://localhost:8000/api/v1/movies/1/crew
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MTE5NzAxOTMsImV4cCI6MTcxMjAxMzM5Mywicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiai53b25nQG1haWwuY29tIn0.cp5GY4KUJWdL5vHWUQRXplitNpXHEWSE2T8I5N4CUamXNKjOPrqqzWog81P49y5rNcjZfIp6tYKVE2axrxktzThh0nZF3JS7vcvnWknNspjqJwyvJYt2Dsi_eS3ivo8RWKMr4We5zrcytgBwJeh3SsfTr0pj75gAjZkjHjqFi5EdrRKGfa96P7FZNhqaIQ6R7aLM9DVGQvATnwlLcsEHJUKNShB8rRct5yYK537wxB8H_tK2MTUv7Q5IiU_7IvdYs01qqQ4Eoweli-2WImyDx3eb-gUlFbbevUtvRtW6pHnEZC22VOSeOj-mCzd0lm_LUUelHx6k6Isj9JRyv01HUQ