controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: annotation

# The routes to expose to the API
api_login_check:
    path: /api/login_check

# Add the Swagger UI route
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }